version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    build: backend/.
    volumes:
      - ./backend/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db