version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JDBC_URL=jdbc:postgresql://db:5432/postgres
    ports:
      - "5432:5432"
    profiles: ["frontend-dev", "backend-dev"]

  backend:
    build: backend/.
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles: ["frontend-dev"]