version: "3.9"
# TODO: Lock image versions
services:
  db:
    image: postgres:bullseye
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JDBC_URL=jdbc:postgresql://0.0.0.0:5432/postgres
    ports:
      - "5432:5432"
    profiles:
      - "frontend-dev"
      - "backend-dev"

  migration:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=postgres migrate
    volumes:
      - ./backend/flyway/sql:/flyway/sql
    profiles:
      - "frontend-dev"
      - "backend-dev"
    depends_on:
      - db

  backend:
    build: backend/.
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/postgres
      - CORS_ENABLED=false
    depends_on:
      - db
    profiles:
      - "frontend-dev"
