/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.Auth;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthRecord extends UpdatableRecordImpl<AuthRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.auth.id</code>.
     */
    public AuthRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.auth.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.auth.encrypted_password</code>.
     */
    public AuthRecord setEncryptedPassword(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.auth.encrypted_password</code>.
     */
    public String getEncryptedPassword() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Auth.AUTH.ID;
    }

    @Override
    public Field<String> field2() {
        return Auth.AUTH.ENCRYPTED_PASSWORD;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEncryptedPassword();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEncryptedPassword();
    }

    @Override
    public AuthRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuthRecord value2(String value) {
        setEncryptedPassword(value);
        return this;
    }

    @Override
    public AuthRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthRecord
     */
    public AuthRecord() {
        super(Auth.AUTH);
    }

    /**
     * Create a detached, initialised AuthRecord
     */
    public AuthRecord(Integer id, String encryptedPassword) {
        super(Auth.AUTH);

        setId(id);
        setEncryptedPassword(encryptedPassword);
    }
}
