/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.NoteCategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteCategoryRecord extends UpdatableRecordImpl<NoteCategoryRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.note_category.id</code>.
     */
    public NoteCategoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.note_category.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.note_category.title</code>.
     */
    public NoteCategoryRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.note_category.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.note_category.description</code>.
     */
    public NoteCategoryRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.note_category.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NoteCategory.NOTE_CATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return NoteCategory.NOTE_CATEGORY.TITLE;
    }

    @Override
    public Field<String> field3() {
        return NoteCategory.NOTE_CATEGORY.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public NoteCategoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NoteCategoryRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public NoteCategoryRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public NoteCategoryRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoteCategoryRecord
     */
    public NoteCategoryRecord() {
        super(NoteCategory.NOTE_CATEGORY);
    }

    /**
     * Create a detached, initialised NoteCategoryRecord
     */
    public NoteCategoryRecord(Integer id, String title, String description) {
        super(NoteCategory.NOTE_CATEGORY);

        setId(id);
        setTitle(title);
        setDescription(description);
    }
}
