/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDateTime;

import jooq.enums.OrganizationRole;
import jooq.tables.UserOrganizationMembership;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserOrganizationMembershipRecord extends UpdatableRecordImpl<UserOrganizationMembershipRecord> implements Record5<Integer, LocalDateTime, Integer, Integer, OrganizationRole> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_organization_membership.id</code>.
     */
    public UserOrganizationMembershipRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_organization_membership.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_organization_membership.created</code>.
     */
    public UserOrganizationMembershipRecord setCreated(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_organization_membership.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.user_organization_membership.user_id</code>.
     */
    public UserOrganizationMembershipRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_organization_membership.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>public.user_organization_membership.organization_id</code>.
     */
    public UserOrganizationMembershipRecord setOrganizationId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.user_organization_membership.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.user_organization_membership.role</code>.
     */
    public UserOrganizationMembershipRecord setRole(OrganizationRole value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_organization_membership.role</code>.
     */
    public OrganizationRole getRole() {
        return (OrganizationRole) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, LocalDateTime, Integer, Integer, OrganizationRole> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, LocalDateTime, Integer, Integer, OrganizationRole> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserOrganizationMembership.USER_ORGANIZATION_MEMBERSHIP.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return UserOrganizationMembership.USER_ORGANIZATION_MEMBERSHIP.CREATED;
    }

    @Override
    public Field<Integer> field3() {
        return UserOrganizationMembership.USER_ORGANIZATION_MEMBERSHIP.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return UserOrganizationMembership.USER_ORGANIZATION_MEMBERSHIP.ORGANIZATION_ID;
    }

    @Override
    public Field<OrganizationRole> field5() {
        return UserOrganizationMembership.USER_ORGANIZATION_MEMBERSHIP.ROLE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreated();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getOrganizationId();
    }

    @Override
    public OrganizationRole component5() {
        return getRole();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreated();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getOrganizationId();
    }

    @Override
    public OrganizationRole value5() {
        return getRole();
    }

    @Override
    public UserOrganizationMembershipRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserOrganizationMembershipRecord value2(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public UserOrganizationMembershipRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserOrganizationMembershipRecord value4(Integer value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public UserOrganizationMembershipRecord value5(OrganizationRole value) {
        setRole(value);
        return this;
    }

    @Override
    public UserOrganizationMembershipRecord values(Integer value1, LocalDateTime value2, Integer value3, Integer value4, OrganizationRole value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserOrganizationMembershipRecord
     */
    public UserOrganizationMembershipRecord() {
        super(UserOrganizationMembership.USER_ORGANIZATION_MEMBERSHIP);
    }

    /**
     * Create a detached, initialised UserOrganizationMembershipRecord
     */
    public UserOrganizationMembershipRecord(Integer id, LocalDateTime created, Integer userId, Integer organizationId, OrganizationRole role) {
        super(UserOrganizationMembership.USER_ORGANIZATION_MEMBERSHIP);

        setId(id);
        setCreated(created);
        setUserId(userId);
        setOrganizationId(organizationId);
        setRole(role);
    }
}
