CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    verified BOOL DEFAULT FALSE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS auth (
    id SERIAL PRIMARY KEY REFERENCES users (id),
    encrypted_password VARCHAR NOT NULL
);
