CREATE TABLE IF NOT EXISTS note (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content VARCHAR NOT NULL,
    verified BOOL DEFAULT FALSE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    author_id SERIAL REFERENCES users (id)
);