/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import jooq.Keys;
import jooq.Public;
import jooq.enums.NoteCategoryAccess;
import jooq.tables.records.UserNotecategoryOwnershipRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNotecategoryOwnership extends TableImpl<UserNotecategoryOwnershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_notecategory_ownership</code>
     */
    public static final UserNotecategoryOwnership USER_NOTECATEGORY_OWNERSHIP = new UserNotecategoryOwnership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserNotecategoryOwnershipRecord> getRecordType() {
        return UserNotecategoryOwnershipRecord.class;
    }

    /**
     * The column <code>public.user_notecategory_ownership.id</code>.
     */
    public final TableField<UserNotecategoryOwnershipRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user_notecategory_ownership.created</code>.
     */
    public final TableField<UserNotecategoryOwnershipRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user_notecategory_ownership.user_id</code>.
     */
    public final TableField<UserNotecategoryOwnershipRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user_notecategory_ownership.category_id</code>.
     */
    public final TableField<UserNotecategoryOwnershipRecord, Integer> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.user_notecategory_ownership.organization_id</code>.
     */
    public final TableField<UserNotecategoryOwnershipRecord, Integer> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.user_notecategory_ownership.note_category_access</code>.
     */
    public final TableField<UserNotecategoryOwnershipRecord, NoteCategoryAccess> NOTE_CATEGORY_ACCESS = createField(DSL.name("note_category_access"), SQLDataType.VARCHAR.asEnumDataType(jooq.enums.NoteCategoryAccess.class), this, "");

    private UserNotecategoryOwnership(Name alias, Table<UserNotecategoryOwnershipRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserNotecategoryOwnership(Name alias, Table<UserNotecategoryOwnershipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_notecategory_ownership</code> table
     * reference
     */
    public UserNotecategoryOwnership(String alias) {
        this(DSL.name(alias), USER_NOTECATEGORY_OWNERSHIP);
    }

    /**
     * Create an aliased <code>public.user_notecategory_ownership</code> table
     * reference
     */
    public UserNotecategoryOwnership(Name alias) {
        this(alias, USER_NOTECATEGORY_OWNERSHIP);
    }

    /**
     * Create a <code>public.user_notecategory_ownership</code> table reference
     */
    public UserNotecategoryOwnership() {
        this(DSL.name("user_notecategory_ownership"), null);
    }

    public <O extends Record> UserNotecategoryOwnership(Table<O> child, ForeignKey<O, UserNotecategoryOwnershipRecord> key) {
        super(child, key, USER_NOTECATEGORY_OWNERSHIP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UserNotecategoryOwnershipRecord, Integer> getIdentity() {
        return (Identity<UserNotecategoryOwnershipRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserNotecategoryOwnershipRecord> getPrimaryKey() {
        return Keys.USER_NOTECATEGORY_OWNERSHIP_PKEY;
    }

    @Override
    public List<UniqueKey<UserNotecategoryOwnershipRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USER_NOTECATEGORY_OWNERSHIP_USER_ID_CATEGORY_ID_KEY);
    }

    @Override
    public List<ForeignKey<UserNotecategoryOwnershipRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_NOTECATEGORY_OWNERSHIP__USER_NOTECATEGORY_OWNERSHIP_USER_ID_FKEY, Keys.USER_NOTECATEGORY_OWNERSHIP__USER_NOTECATEGORY_OWNERSHIP_CATEGORY_ID_FKEY, Keys.USER_NOTECATEGORY_OWNERSHIP__USER_NOTECATEGORY_OWNERSHIP_ORGANIZATION_ID_FKEY);
    }

    private transient Users _users;
    private transient NoteCategory _noteCategory;
    private transient Organization _organization;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.USER_NOTECATEGORY_OWNERSHIP__USER_NOTECATEGORY_OWNERSHIP_USER_ID_FKEY);

        return _users;
    }

    /**
     * Get the implicit join path to the <code>public.note_category</code>
     * table.
     */
    public NoteCategory noteCategory() {
        if (_noteCategory == null)
            _noteCategory = new NoteCategory(this, Keys.USER_NOTECATEGORY_OWNERSHIP__USER_NOTECATEGORY_OWNERSHIP_CATEGORY_ID_FKEY);

        return _noteCategory;
    }

    /**
     * Get the implicit join path to the <code>public.organization</code> table.
     */
    public Organization organization() {
        if (_organization == null)
            _organization = new Organization(this, Keys.USER_NOTECATEGORY_OWNERSHIP__USER_NOTECATEGORY_OWNERSHIP_ORGANIZATION_ID_FKEY);

        return _organization;
    }

    @Override
    public UserNotecategoryOwnership as(String alias) {
        return new UserNotecategoryOwnership(DSL.name(alias), this);
    }

    @Override
    public UserNotecategoryOwnership as(Name alias) {
        return new UserNotecategoryOwnership(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserNotecategoryOwnership rename(String name) {
        return new UserNotecategoryOwnership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserNotecategoryOwnership rename(Name name) {
        return new UserNotecategoryOwnership(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, LocalDateTime, Integer, Integer, Integer, NoteCategoryAccess> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
