/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import jooq.Indexes;
import jooq.Keys;
import jooq.Public;
import jooq.enums.NoteAccess;
import jooq.tables.records.UserNoteOwnershipRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNoteOwnership extends TableImpl<UserNoteOwnershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_note_ownership</code>
     */
    public static final UserNoteOwnership USER_NOTE_OWNERSHIP = new UserNoteOwnership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserNoteOwnershipRecord> getRecordType() {
        return UserNoteOwnershipRecord.class;
    }

    /**
     * The column <code>public.user_note_ownership.id</code>.
     */
    public final TableField<UserNoteOwnershipRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user_note_ownership.created</code>.
     */
    public final TableField<UserNoteOwnershipRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user_note_ownership.user_id</code>.
     */
    public final TableField<UserNoteOwnershipRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user_note_ownership.note_id</code>.
     */
    public final TableField<UserNoteOwnershipRecord, Integer> NOTE_ID = createField(DSL.name("note_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user_note_ownership.organization_id</code>.
     */
    public final TableField<UserNoteOwnershipRecord, Integer> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user_note_ownership.note_access</code>.
     */
    public final TableField<UserNoteOwnershipRecord, NoteAccess> NOTE_ACCESS = createField(DSL.name("note_access"), SQLDataType.VARCHAR.asEnumDataType(jooq.enums.NoteAccess.class), this, "");

    private UserNoteOwnership(Name alias, Table<UserNoteOwnershipRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserNoteOwnership(Name alias, Table<UserNoteOwnershipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_note_ownership</code> table reference
     */
    public UserNoteOwnership(String alias) {
        this(DSL.name(alias), USER_NOTE_OWNERSHIP);
    }

    /**
     * Create an aliased <code>public.user_note_ownership</code> table reference
     */
    public UserNoteOwnership(Name alias) {
        this(alias, USER_NOTE_OWNERSHIP);
    }

    /**
     * Create a <code>public.user_note_ownership</code> table reference
     */
    public UserNoteOwnership() {
        this(DSL.name("user_note_ownership"), null);
    }

    public <O extends Record> UserNoteOwnership(Table<O> child, ForeignKey<O, UserNoteOwnershipRecord> key) {
        super(child, key, USER_NOTE_OWNERSHIP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_NOTE_OWNERSHIP_ACCESS, Indexes.USER_NOTE_OWNERSHIP_NOTE_ID, Indexes.USER_NOTE_OWNERSHIP_USER_ID);
    }

    @Override
    public Identity<UserNoteOwnershipRecord, Integer> getIdentity() {
        return (Identity<UserNoteOwnershipRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserNoteOwnershipRecord> getPrimaryKey() {
        return Keys.USER_NOTE_OWNERSHIP_PKEY;
    }

    @Override
    public List<UniqueKey<UserNoteOwnershipRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USER_NOTE_OWNERSHIP_USER_ID_NOTE_ID_KEY);
    }

    @Override
    public List<ForeignKey<UserNoteOwnershipRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_NOTE_OWNERSHIP__USER_NOTE_OWNERSHIP_USER_ID_FKEY, Keys.USER_NOTE_OWNERSHIP__USER_NOTE_OWNERSHIP_NOTE_ID_FKEY, Keys.USER_NOTE_OWNERSHIP__USER_NOTE_OWNERSHIP_ORGANIZATION_ID_FKEY);
    }

    private transient Users _users;
    private transient Note _note;
    private transient Organization _organization;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.USER_NOTE_OWNERSHIP__USER_NOTE_OWNERSHIP_USER_ID_FKEY);

        return _users;
    }

    /**
     * Get the implicit join path to the <code>public.note</code> table.
     */
    public Note note() {
        if (_note == null)
            _note = new Note(this, Keys.USER_NOTE_OWNERSHIP__USER_NOTE_OWNERSHIP_NOTE_ID_FKEY);

        return _note;
    }

    /**
     * Get the implicit join path to the <code>public.organization</code> table.
     */
    public Organization organization() {
        if (_organization == null)
            _organization = new Organization(this, Keys.USER_NOTE_OWNERSHIP__USER_NOTE_OWNERSHIP_ORGANIZATION_ID_FKEY);

        return _organization;
    }

    @Override
    public UserNoteOwnership as(String alias) {
        return new UserNoteOwnership(DSL.name(alias), this);
    }

    @Override
    public UserNoteOwnership as(Name alias) {
        return new UserNoteOwnership(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserNoteOwnership rename(String name) {
        return new UserNoteOwnership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserNoteOwnership rename(Name name) {
        return new UserNoteOwnership(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, LocalDateTime, Integer, Integer, Integer, NoteAccess> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
