/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Auth;
import jooq.tables.FlywaySchemaHistory;
import jooq.tables.Note;
import jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.auth</code>.
     */
    public static final Auth AUTH = Auth.AUTH;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.note</code>.
     */
    public static final Note NOTE = Note.NOTE;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
