/*
 * This file is generated by jOOQ.
 */
package jooq.enums;


import jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum NoteAccess implements EnumType {

    WRITE("WRITE"),

    READ("READ");

    private final String literal;

    private NoteAccess(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "note_access";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static NoteAccess lookupLiteral(String literal) {
        return EnumType.lookupLiteral(NoteAccess.class, literal);
    }
}
