micronaut:
  application:
    name: backend
  server:
    port: 8080
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://0.0.0.0:5432/postgres`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    dialect: POSTGRES
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    entity-scan:
      packages: 'com.note'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true




